// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDqRyMy1I5iwPGxkQx96tVInUkbqcplk',
    appId: '1:402478699782:web:2ef8ea8b5f1c8f94b4fa87',
    messagingSenderId: '402478699782',
    projectId: 'jewellery-87fc0',
    authDomain: 'jewellery-87fc0.firebaseapp.com',
    storageBucket: 'jewellery-87fc0.firebasestorage.app',
    measurementId: 'G-BLPV8J2K8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb0FcC-jMNq_mtlgh2FH5Izv6arLNCNjo',
    appId: '1:402478699782:android:7928c80a784e3c5ab4fa87',
    messagingSenderId: '402478699782',
    projectId: 'jewellery-87fc0',
    storageBucket: 'jewellery-87fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEDZtQIKHGyg_A4V2DN5bNUxMilZt6ME',
    appId: '1:402478699782:ios:e88c1470a6667df4b4fa87',
    messagingSenderId: '402478699782',
    projectId: 'jewellery-87fc0',
    storageBucket: 'jewellery-87fc0.firebasestorage.app',
    iosBundleId: 'com.example.newsSnack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEDZtQIKHGyg_A4V2DN5bNUxMilZt6ME',
    appId: '1:402478699782:ios:e88c1470a6667df4b4fa87',
    messagingSenderId: '402478699782',
    projectId: 'jewellery-87fc0',
    storageBucket: 'jewellery-87fc0.firebasestorage.app',
    iosBundleId: 'com.example.newsSnack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbDqRyMy1I5iwPGxkQx96tVInUkbqcplk',
    appId: '1:402478699782:web:929276fb01b6b182b4fa87',
    messagingSenderId: '402478699782',
    projectId: 'jewellery-87fc0',
    authDomain: 'jewellery-87fc0.firebaseapp.com',
    storageBucket: 'jewellery-87fc0.firebasestorage.app',
    measurementId: 'G-1Z65KXLNQ0',
  );
}
